### ISSUE TITLE
Стрелка уехала

### ISSUE THREAD

**Issue by anleshch** [Cheewbacca/BudPartner#124]
http://joxi.ru/vAW73YxuBjq6EA

**Comment by Byelmanov** [comment]
it looks good on localhost

**Comment by quallrum** [comment]
Button text appears to be slightly higher that it should be on screens with width <1200
Following screenshots are taken from the front repo

![image](https://user-images.githubusercontent.com/34860412/127899108-102c456a-0535-470f-aac5-5e6db0bad8a7.png)
![image](https://user-images.githubusercontent.com/34860412/127899509-34841888-998e-419b-94e1-f978a8e1d683.png)
