### ISSUE TITLE
Ниже атачу список блоков на страницах. Если таска не понятна, то напиши мне, объясню детальнее.

### ISSUE THREAD

**Issue by anleshch** [Cheewbacca/BudPartner#138]
http://joxi.ru/YmEQnkjUBZ3l8m

Кухни
-Мебельные фасады
-Покраска изделий
-Столы
-Прихожие
-Гостиные
-Шкафы

Гостиные
-Шкафы
-Гардеробные
-Детские комнаты
-Стеновые панели
-Спальни
-Мебельные фасады

Спальни
-Детские комнаты
-Шкафы
-Гардеробные
-Стеновые панели
-Прихожие
-Гостиные

Шкафы, гардеробные (Оставляем только шкафы, гардеробные будут вместо обшивка мебели)
-Гардеробные
-Гостиные
-Спальни
-Детские комнаты
-Прихожие
-Мебельные фасады

Ванные комнаты
-Прихожие
-Двери
-Спальни
-Покраска изделий
-Мебельные фасады
-Гардеробные

Детские комнаты
-Гардеробные
-Шкафы
-Спальни
-Гостиные
-Стеновые панели
-Прихожие

Мебель для бизнеса
-Столы
-Лестницы
-Кухни
-Шкафы
-Двери
-Гостиные

Столы
-Кухни
-Прихожие
-Гостиные
-Мебель для бизнеса
-Гардеробные
-Спальни

Прихожие
-Шкафы
-Гардеробные
-Детские комнаты
-Ванные комнаты
-Кухни
-Стеновые панели

Двери
-Столы
-Лестницы
-Покраска изделий
-Мебельные фасады
-Стеновые панели
-Гостиные

Обшивка мебели (Здесь будут гардеробные, так как их со шкафами обязательно нужно разделить, и услуг по обшивке у нас нет)
-Прихожие
-Шкафы
-Гостиные
-Спальни
-Детские
-Мебельные фасады

Стеновые панели
-Покраска изделий
-Мебельные фасады
-Лестницы
-Гардеробные
-Гостиные
-Мебель для бизнеса

Лестницы
-Стеновые панели
-Покраска изделий
-Мебельные фасады
-Гардеробные
-Двери
-Прихожие

Покраска изделий 
-Мебельные фасады
-Стеновые панели
-Двери
-Лестницы
-Кухни
-Гостиные

Мебельные фасады
-Покраска изделий
-Кухни
-Гостиные
-Спальны
-Гардеробные
-Двери

**Comment by quallrum** [comment]
This block is called "Recommendations" and it is configured from admin panel for each Service. So I would guess that this task should be done exactly by site manager for two reason: in order to learn how to use an admin panel and obviously he knows better how this section should be configured for each Service. Feel free to reopen if you realy want to force us to do it :)
