### ISSUE TITLE
На страницах услуг до сих пор при нажатии на "Оставить заявку" действует якорная ссылка вниз, а не открывается модалка

### ISSUE THREAD

**Issue by anleshch** [Cheewbacca/BudPartner#145]
http://joxi.ru/Dr8g6nkfJzG0PA

**Comment by Byelmanov** [comment]
@quallrum the same on the index page, on localhost it works, please check that all needed scripts are included

**Comment by quallrum** [comment]
Well, I think it works, both on local and demo server, no actions from me. Please make sure you have all cache cleared. Have checked it on home page, services list page and specific service page.

@anleshch @Byelmanov

**Comment by Byelmanov** [comment]
@quallrum checked it in incognito mode and it's not working
