### ISSUE TITLE
"Our works" section responsive failure

### ISSUE THREAD

**Issue by quallrum** [Cheewbacca/BudPartner#50]
The result of resizing window without refreshing the page. This case imho is probable enough so should be fixed. For example it may occur when you change phone orientation to landscape and back

![image](https://user-images.githubusercontent.com/34860412/97120324-ea29d580-171e-11eb-9445-b220404ac34f.png)

**Comment by Cheewbacca** [comment]
Hello, I tried several times to achieve the same result as in the screenshot, but I realy can`t do it. So I went to Dev Tools and tried to change phone orientation to landscape and back. I become something like this: 
https://video.drift.com/v/ab7T6HCjwWh/

I'm not sure if this is a serious problem that can be achieved from a mobile device. But if u still think so, please provide steps to become this issue, or close it, if is no longer relevant

**Comment by quallrum** [comment]
Well, seems like I found steps to reproduce:

- Open the page with desktop width
- Scroll to "Our works" section to activate parallax
- Scroll to top until this block disappeared
- Change width to < 767px
- Scroll back and take a look on this section

The problem is that when you scroll to top in desctop mode pictures are moving to top due to parallax. But if you then change width to mobile, parallax will be disabled and pictures will be fixed at its last positions (at the top) and can't move down during scroll
