### ISSUE TITLE
Ability to build services page dynamicaly

### ISSUE THREAD

**Issue by quallrum** [Cheewbacca/BudPartner#57]
Now I cant insert proper image to service card because it is defined in stylesheet.
Please dont use css to determine the content of the page and leave the ability to set the image dynamicaly, for example using inline styles:
```
<div class="content p25" style="background-image: url('{{ serice.image|media }}')">...</div>
```
To create shadows you can use additional blocks or pseudoelements (better way imho) instead of multiple values of `background` property.

![image](https://user-images.githubusercontent.com/34860412/99728023-767eac80-2ac1-11eb-857e-f8926c37c08a.png)

**Comment by quallrum** [comment]
Just noticed that single service page have the same problem, please fix that too

![image](https://user-images.githubusercontent.com/34860412/99730625-6ff23400-2ac5-11eb-819f-90bd39fd6d8a.png)

**Comment by Cheewbacca** [comment]
@quallrum please discuss this with @Byelmanov, I`ve already assigned him to this issue. 
You can start a chat right here

**Comment by Cheewbacca** [comment]
@Byelmanov
**UPDATE**: please assign to me a pull request submitting into the dev branch, looks like we have conflicts and it can affect homepage

**Comment by quallrum** [comment]
Please provide the same ability for "You may like" section, I also need to set background images here dynamicly too

![image](https://user-images.githubusercontent.com/34860412/100549441-a2492180-327b-11eb-9f24-78f7c9c5c0c2.png)

**Comment by quallrum** [comment]
And for service pages' header too)
![image](https://user-images.githubusercontent.com/34860412/100931222-e7c35400-34f2-11eb-9980-6f313b0e3636.png)
