### ISSUE TITLE
Dont use image paths explicitly

### ISSUE THREAD

**Issue by quallrum** [Cheewbacca/BudPartner#71]
These paths are different in cms so they shouldn't be used in styles and scripts. If there arent any other ways to do it, you can use data attributes to allow me to insert there correct paths. I found such problems in following files but it probably may appeare elsewhere so please check out your code: 
```
themes/budpartner/assets/js/main.js
themes/budpartner/assets/css/main.css
```
![image](https://user-images.githubusercontent.com/34860412/100547008-23e58300-326d-11eb-9a13-1cbde8910065.png)
![image](https://user-images.githubusercontent.com/34860412/100547131-c140b700-326d-11eb-80aa-6632a796a86f.png)

P.S. Now I figured out another way to avoid such problems - manualy change paths when I update styles and scripts, but I'm not sure this is a good solution because I (or other maintainer) may forget to do that. And also its easy to miss some path(s). As of there is no single way, welcome to conversation, lets find the best solution)

**Comment by Cheewbacca** [comment]
@quallrum if I understood correctly you told me about arrows near text? 
I believe that they can remain static and have a hard-coded path.
And also I hope that nobody else will touch it 👍

**Comment by quallrum** [comment]
Yet another problem with paths:
![image](https://user-images.githubusercontent.com/34860412/100662094-1c050c00-335d-11eb-8511-b8e606da246d.png)
![image](https://user-images.githubusercontent.com/34860412/100662183-37701700-335d-11eb-97df-58017fece721.png)

Probably you can use following paths in styles. But it restricts you to place images only in `img` near the directory with styles
![image](https://user-images.githubusercontent.com/34860412/100662348-6edec380-335d-11eb-8fba-1b59264d3cfc.png)
![image](https://user-images.githubusercontent.com/34860412/100662364-79995880-335d-11eb-9141-aa7a019e83e1.png)

**Comment by Cheewbacca** [comment]
@quallrum header.html
