### ISSUE TITLE
Callback form improvements

### ISSUE THREAD

**Issue by quallrum** [Cheewbacca/BudPartner#81]
### Sections

![image](https://user-images.githubusercontent.com/34860412/102637656-fea6af00-415e-11eb-8e80-a439e23b3ce4.png)
![image](https://user-images.githubusercontent.com/34860412/102637670-049c9000-415f-11eb-9749-38514386a056.png)

It would be great if you move callback form from footer (1st picture) to separate section (2nd section) to allow me to create a component "callback section" with ability to choose type of it. 

### General

![image](https://user-images.githubusercontent.com/34860412/102639142-475f6780-4161-11eb-987f-5583e7853176.png)

As I mentioned above, I want to create one or several components for callback form. Currently I came up with two of them - component for section form and component for "call me" button that opens a modal window. And there will be no separated handlers for each form (as of it is a component and could be added anywhere) but the global handler that processes any form with specific class added as a callback form. At the same time, callback button should have an attribute that specifies which modal with form shoul be opened. 

Please let me know what do you think about that, could it be done or we should think out an other way?

**Comment by quallrum** [comment]
@Cheewbacca, `this` here is the `window` object, not the form you expect.

![image](https://user-images.githubusercontent.com/34860412/103173547-701fe500-4864-11eb-8e88-acf575b02ff0.png)

Try to use here `sendForm.call(this, $(this).data('form'))` instead.

![image](https://user-images.githubusercontent.com/34860412/103173603-b70dda80-4864-11eb-857a-92364e540c56.png)

**Comment by quallrum** [comment]
Response examples

Success response
```
200 OK

{
    "success": true,
    "message": "Заявка успешно отправлена, наши менеджеры свяжутся з Вами в ближайшее время!"
}
```
Validation error response
```
422 Unprocessable Entity

{
    "success": false,
    "message": "Форма заполена некоректно!",
    "errors": {
        "name": ["Введите имя", "Масимальная длинна имени - 150 символов"],
        "phone": ["Введите телефон", "Введите телефон в формате 380123456789"]
    }
}
```

Server error reponse
Currently, my backend code doesn't send the 500 status code explicitly, but it is highly recommended to process this status because cms will return this code if some errors occured on its side.

**Comment by quallrum** [comment]
![image](https://user-images.githubusercontent.com/34860412/103174590-1e7b5880-486c-11eb-9c7d-c26b1a1a28fb.png)

**Comment by Cheewbacca** [comment]
Check new update
