### ISSUE TITLE
добавить ссылку на материалы

### ISSUE THREAD

**Issue by anleshch** [Cheewbacca/BudPartner#91]
https://drive.google.com/drive/folders/0BxovqK_79Y-yaFVfUkx1UjZBYlk - вот ссылка на материалы.

добавьте пожалуйста сюда:

http://joxi.ru/bmoPWOwCykVLl2 - тут и во всех подобных (это на всех страницах услуг)

http://joxi.ru/brRXl8RTOMgpW2 - и тут (это на стр покраски изделий)

**Comment by quallrum** [comment]
@anleshch @Byelmanov so header "Materials" should be a link to Google Drive folder you provided?

**Comment by anleshch** [comment]
@quallrum да
