### ISSUE TITLE
стрелочка при ховере

### ISSUE THREAD

**Issue by anleshch** [Cheewbacca/BudPartner#98]
http://joxi.ru/E2pPdkwCGbRQL2 тут у кухонь на ховер должна тоже стрелочка появляться

**Comment by Byelmanov** [comment]
On localhost it works, check it again please @quallrum

**Comment by quallrum** [comment]
Проблема в script, для first element with нулевой index не обрабатываются events и поэтому arrow не появляется
![image](https://user-images.githubusercontent.com/34860412/105614967-8e322400-5dd5-11eb-97d5-9d19dda3710b.png)
